// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loghvhhcwtmtwxmtjumk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZ2h2aGhjd3RtdHd4bXRqdW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDU1MzIsImV4cCI6MjA2ODkyMTUzMn0.q2uKLOh6qc_-VWt4UpX9O1rKxwpkxFCHeFte538b6E0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});